/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogOperationalExcellenceInRailRouteImport } from './routes/blog.operational-excellence-in-rail'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogOperationalExcellenceInRailRoute =
  BlogOperationalExcellenceInRailRouteImport.update({
    id: '/blog/operational-excellence-in-rail',
    path: '/blog/operational-excellence-in-rail',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog/operational-excellence-in-rail': typeof BlogOperationalExcellenceInRailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog/operational-excellence-in-rail': typeof BlogOperationalExcellenceInRailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog/operational-excellence-in-rail': typeof BlogOperationalExcellenceInRailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/blog/operational-excellence-in-rail'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog/operational-excellence-in-rail'
  id: '__root__' | '/' | '/blog/operational-excellence-in-rail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogOperationalExcellenceInRailRoute: typeof BlogOperationalExcellenceInRailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/operational-excellence-in-rail': {
      id: '/blog/operational-excellence-in-rail'
      path: '/blog/operational-excellence-in-rail'
      fullPath: '/blog/operational-excellence-in-rail'
      preLoaderRoute: typeof BlogOperationalExcellenceInRailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogOperationalExcellenceInRailRoute: BlogOperationalExcellenceInRailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
